PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?var_book
	WHERE {
		?var_book rdf:type <http://dbpedia.org/ontology/Book> .
		?var_book <http://dbpedia.org/ontology/isbn> ?var_isbn .
	}
